version: '3'
services:
  app:
    container_name: node-mongo-app
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'